/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
    {
        _id: "RE_WXlSib3Y",
        creator: "PowerDrift",
        creatorId: "AKedOLS3H1iDFct-st71_rCt-dWiUPYkt5PCTsI_B92T",
        title: "Dakar 2019 | Ep 1 | The toughest rally on the planet ",
        description:
            "The 2019 Dakar Rally was hosted by just one country for the first time in its 42-year history - Peru. Traversing 5,000 kms of the Peruvian terrain over 10 stages can take a toll on even the most hardened rally racers across the world! However, this didn't stop 534 brave competitors from lining up at the ceremonial start in Lima, Peru. Among these bravehearts were CS Santhosh, Joaquim Rodrigues and Oriol Mena, the flagbearers for Hero MotoSports Team Rally. As one of the only two Indian teams on the grid, Hero is carrying a fair bit of weight on its shoulders.",
        views: "145,253",
        category: "Dakar",
        uploadDate: "Dec 3, 2019",
    },
    {
        _id: "aohn1w96FEY",
        creator: "Itchy Boots",
        creatorId: "AKedOLQO28MOUeXDxzk_EQ5k3ZPCVO1ANn7NTEuAqF2IGw",
        title: "Solo off-roading at the border between Namibia and Angola",
        description:
            "In this episode I am following the Kunene river, right at the border between Namibia and Angola. The road is a little tricky sometimes but the scenery absolutely magnificent!! ",
        views: "276,169",
        category: "Travel",
        uploadDate: "Aug 4, 2021",
    },
    {
        _id: "MphoOGPzkzk",
        creator: "PowerDrift",
        creatorId: "AKedOLS3H1iDFct-st71_rCt-dWiUPYkt5PCTsI_B92T",
        title: "Dakar 2019 | Ep 2 | Never give up!",
        description:
            "In the previous episode, team Hero Motosport came out unscratched in the first three stages of Dakar. Now, seven long and harsh stages of the rally lay in the path of CS Santosh, Joaquim Rodrigues and Oriol Mena. With challenges like fog and fesh-fesh ready to play spoilsport, will our heroes be able to pull it through?",
        views: "145,253",
        category: "Dakar",
        uploadDate: "Dec 4, 2019",
    },
    {
        _id: "MWl1GpJ5AOo",
        creator: "DW REV - Cars & Mobility",
        creatorId: "AKedOLSpa6gTIElSZpLTdsbOTtaYdEbsDUI2ieHgKX6C",
        title: "CS Santosh's Recovery After Dakar 2021 Horror Accident",
        description:
            "CS Santosh is considered one of India's most accomplished motorsport athletes, with three Dakar finishes under his belt. At the 2021 Dakar, the Hero MotoSports Team Rally rider suffered a horrific crash on Stage 4 of the rally. He was placed in an induced coma to aid his recovery. When he finally woke up, he was a changed person. In this warts-and-all-interview, CS Santosh sits down with DW REV and talks us through his journey of recovery, his fight to find himself again, and his concerted efforts to someday be back on the motorcycle competing in the dunes. ",
        views: "151,097",
        category: "Dakar",
        uploadDate: "Dec 11, 2021",
    },
    {
        _id: "u3O_ifL9K0U",
        creator: "Autocar India",
        creatorId: "AKedOLRbI-xI_kQi685P7v3pfPbsAQ3qQ9JMakERpbzDgQ",
        title: "Motocross Days At Big Rock MotoPark With CS Santosh",
        description:
            "Kartikeya Singhee spends 2 days at Big Rock Motopark with by motocross champion and India's Dakar hopeful CS Santosh. Watch as he gets a dose of motocross basics, some big air and a taste of extreme off road riding!",
        views: "33,822",
        category: "Off Road Basics",
        uploadDate: "Jun 27, 2014",
    },
    {
        _id: "A8zqGnI3gNY",
        creator: "Red Bull",
        creatorId: "AKedOLQIf7hyEzlX3IyKiMOKjkQz7pS8eKsPnVXe08_MxQ",
        title: "Impossible Moments In Dakar Rally History ",
        description:
            "This is what it looks like when things go wrong at the most prestigious off-road rally on the planet: Dakar Rally! ",
        views: "443,212",
        category: "Dakar",
        uploadDate: "Jan 4, 2021",
    },
    {
        _id: "YkYXmNMwNvQ",
        creator: "Dakar",
        creatorId: "AKedOLSuoaMilD2UyuKupQ59D0dwusIP4GAuffXavHJPvw",
        title: "The Dakar for Newbies | Dakar 2022",
        description:
            "What is the Dakar? How does it work? Who is competing? What's new on the 2022 edition? If you're wondering why this race is THAT legendary, all you need to do is watch this video",
        views: "443,212",
        category: "Dakar",
        uploadDate: "Dec 30, 2021",
    },
    {
        _id: "5PlozYDXBeA",
        creator: "FortNine",
        creatorId: "AKedOLSoxgXDjtLyoa4fW-Ya4Tt4sImuFqCY-4FZvTCn",
        title: "Adventure Motorcycle Survival Skills",
        description:
            "If you ride off-road or to remote places, there's a chance you might find yourself stuck or stranded at some point. Don’t sweat it though. Your mighty steed is also a small hardware store on two wheels. We show you how to use it to survive. ",
        views: "626,324",
        category: "Tips n Tricks",
        uploadDate: "Apr 1, 2020",
    },
    {
        _id: "ALXCSdjkjgA",
        creator: "Murthaza Junaid",
        creatorId: "AKedOLRUX2NYkb5kbl6PsCe8Q6RbMd3kox4yiiaXzMThQQ",
        title: "Art of Motorcycling- Off road Basics",
        description:
            "In This Video We continue from where we had left, Focussed towards Individual attendees Problems and  As this was the last day of the camp We had a good time sharing stories and making memories.",
        views: "56,452",
        category: "Off Road Basics",
        uploadDate: "Jan 15, 2018",
    },
    {
        _id: "UsOGqaTH3d0",
        creator: "Bret Tkacs",
        creatorId: "AKedOLTah3wO8rXzUJAUk_Mc2yqGPUTdk6L5809pq9jaoQ",
        title: "How to stand properly riding off-road",
        description:
            "Standing offroad is a complex composition of action, control, balance and understanding. This video covers the first layer of understand how to stand off-road effectively focusing on how to stand from a seated position, how to sit when needed, how to lock in.",
        views: "139,131",
        category: "Off Road Basics",
        uploadDate: "Feb 19, 2021",
    },
    {
        _id: "U_wma4-889E",
        creator: "Red Bull Rally",
        creatorId: "AKedOLRHpi9_z8DhkczbgfnaWgDqmRed0HQe9glFV-qM",
        title: "How to stand properly riding off-road",
        description:
            "In an ocean with no water, riding raves that never meet a beach, the worlds most skilled pilots and drivers hunt the line to rally raid victory. Nothing defines off-road racing like ripping in the dunes. Join us as we hear from riders and drivers, how to navigate the sand dunes of rally raid racing.",
        views: "139,131",
        category: "Off Road Basics",
        uploadDate: "Dec 28, 2021",
    },
    {
        _id: "qp0deztLqgU",
        creator: "Itchy Boots",
        creatorId: "AKedOLQO28MOUeXDxzk_EQ5k3ZPCVO1ANn7NTEuAqF2IGw",
        title: "I learned how to motocross!!",
        description:
            "In this episode, Marcel van Drunen from www.supermotoschool.nl is teaching me how to motocross. What an absolute blast!! I also got to race with Jayson van Drunen",
        views: "448,434",
        category: "Off Road Basics",
        uploadDate: "Dec 7, 2020",
    },
    {
        _id: "xtJeO1cmFyc",
        creator: "Sagar Sheldekar",
        creatorId: "AKedOLQlE3hy8Q8KZPIsTEJ95d6yh5H9hFSjzrkjCvONuA",
        title: "Xpulse 200 BS6: Rally Kit Review",
        description:
            "After long last, Sarge finally gets his hands on the BS6 Hero Xpulse 200 full loaded with the Rally kit. For just Rs. 38,000, it has the makings of transforming the Xpulse into the most capable offroad weapon that you can buy today. But can it deliver? Sarge hops on to find out.",
        views: "139,131",
        category: "Travel",
        uploadDate: "Dec 14, 2020",
    },
    {
        _id: "UBXs6syINkM",
        creator: "FortNine",
        creatorId: "AKedOLSoxgXDjtLyoa4fW-Ya4Tt4sImuFqCY-4FZvTCn",
        title: "Top 10 Off-Roading Mods For Your Adventure Motorcycle",
        description:
            "Thinking of taking your off-roading skills to the next level? Or are you adventure riding beginner looking for some help? Here are some tips to get you ready!",
        views: "607,669",
        category: "Tips n Tricks",
        uploadDate: "Jul 5, 2017",
    },
    {
        _id: "HUZINsU40Fk",
        creator: "Itchy Boots",
        creatorId: "AKedOLQO28MOUeXDxzk_EQ5k3ZPCVO1ANn7NTEuAqF2IGw",
        title: "Itchy Boots tries Enduro - THIS IS HARD!",
        description:
            "In this episode, I am trying the ultimate king of the off-road motorcycle sports: ENDURO! And well, was that a bit more difficult than I anticipated. The tall, aggressive enduro bike threw me off a few times, so I switched to an electric KTM Freeride. With that lower and easier bike, it was still technical and difficult but a lot more manageable! ",
        views: "448,434",
        category: "Travel",
        uploadDate: "Jan 4, 2021",
    },
    {
        _id: "oOD9NnTevH0",
        creator: "MOTOTREK",
        creatorId: "AKedOLRrnwkt7BuMv2kyzjxo2r4ZHRjJolhtKqYJP6DDBA",
        title: "Easy to Expert Motorcycle Mounting & Dismounting Techniques",
        description:
            "There's more than one way to get on and off your motorcycle, and more than a few reasons to learn them all. Professional motorcycle instructor Cassie Maier teaches how you can save tons of energy once you master a variety of mounting and dismounting techniques, which are all especially useful on loaded adventure bikes in off-road environments. ",
        views: "448,434",
        category: "Tips n Tricks",
        uploadDate: "Nov 28, 2020",
    },
    {
        _id: "i8rywrWuAqw",
        creator: "MOTOTREK",
        creatorId: "AKedOLRrnwkt7BuMv2kyzjxo2r4ZHRjJolhtKqYJP6DDBA",
        title: "Learn How To Ride Fast & Safe Around Corners on Dirt",
        description:
            "Cornering at speed off-road is fun! The techniques for riding fast around low-traction corners are different than for cornering on paved roads. Professional riding instructor Dusty Wessels teaches you all you need to ride your adventure bike fast and safe on dirt",
        views: "466,070",
        category: "Tips n Tricks",
        uploadDate: "Feb 28, 2020",
    },
    {
        _id: "3A52heoOdek",
        creator: "Bret Tkacs",
        creatorId: "AKedOLTah3wO8rXzUJAUk_Mc2yqGPUTdk6L5809pq9jaoQ",
        title: "Do handlebar risers really help?",
        description:
            "After a full day of fitting and measuring riser to confirm what I have learned teaching riders over the past 27 years this video is about everything you need to know before choosing to put risers on your motorcycle.",
        views: "466,070",
        category: "Tips n Tricks",
        uploadDate: "Mar 9, 2022",
    },
    {
        _id: "m4eTI583DDQ",
        creator: "Knox Armour",
        creatorId: "AKedOLS3H1iDFct-st71_rCt-dWiUPYkt5PCTsI_B92T",
        title: "Royal Enfield Himalayan off road Raw footage - KNOX",
        description:
            "Royal Enfield Himalayan off road Raw footage. Last month we released our review of the Royal Enfield Himalayan which you guys seemed to really like, it’s a great bike that really comes into its own off the tarmac, so we thought we’d share a raw clip of us riding one of the trails we took it on in the Lake District.",
        views: "72,116",
        category: "Travel",
        uploadDate: "Mar 7, 2021",
    },
    {
        _id: "wCwPLCaEcBs",
        creator: "Red Bull Motosports",
        creatorId: "AKedOLRHpi9_z8DhkczbgfnaWgDqmRed0HQe9glFV-qM",
        title: "Offroad Enduro Racing in Rugged Terrain: Day 2",
        description:
            "Day 2 of the Red Bull Minas Riders hard enduro rally kicks off with the first full day of off-road racing, featuring 165km of ass-kicking terrain. It's steep, it's rough, and it's completely unforgiving. ",
        views: "466,832",
        category: "Travel",
        uploadDate: "Apr 20, 2016",
    },
    {
        _id: "UHkVHDFNUqU",
        creator: "Bret Tkacs",
        creatorId: "AKedOLTah3wO8rXzUJAUk_Mc2yqGPUTdk6L5809pq9jaoQ",
        title: "Techniques for riding up hills",
        description:
            "Join me at Penmerryl Farm in VA for a lesson on ascending hills. Start with the basics and follow Paul Solomonson and myself as we take you to more challenging realistic hills you will find on trails.",
        views: "99,702",
        category: "Tips n Tricks",
        uploadDate: "Apr 8, 2022",
    },
    {
        _id: "Uf64i-7QjzA",
        creator: "MidWest MX",
        creatorId: "AKedOLRIzxtWF4LZ3cUcQjlfTNTzRS8mRvQNH0kb1A2iJg",
        title: "Dirt Bike Ride From Hell - Enduro",
        description:
            "Well this was a challenge! Some really hard enduro in the woods and we get lost in the middle of nowhere down a horrible trail! This really was a dirt bike ride from hell. Getting lost is never fun, especially when you end up down a trail as bad as this one in a new area of riding.",
        views: "397,319",
        category: "Travel",
        uploadDate: "Feb 22, 2020",
    },
    {
        _id: "uRUq26soTSk",
        creator: "Neil Hawker Motolife",
        creatorId: "AKedOLQYV4Rkj6hOAW6-sJZXfQZeoTuJwc1aWB-YQOwQ",
        title: "Dakar Rally 2020 - Raw GOPRO from Neil Hawker Malle Moto.",
        description:
            "This all the Gopro footage from my Dakar Rally 2020 experience from getting lost to riding with a broken arm and getting passed by Rally cars it was a crazy adventure and i want to go back and get a finish",
        views: "110,217",
        category: "Dakar",
        uploadDate: "Jul 8, 2020",
    },
    {
        _id: "fZUbyVqjkxA",
        creator: "Neil Hawker Motolife",
        creatorId: "AKedOLQYV4Rkj6hOAW6-sJZXfQZeoTuJwc1aWB-YQOwQ",
        title: "The Dakar Rally 2021 - vlog 4 - Neil Hawker",
        description:
            "This is the story of my adventure to race in the 2021 Dakar Rally in the Originals by Motul class. It's taken 4 years of preparation and planning to fulfil my dream of racing and finishing the toughest motorsport event in the world.",
        views: "927",
        category: "Dakar",
        uploadDate: "Dec 31, 2021",
    },
    {
        _id: "kdoq7dbFQJY",
        creator: "Red Bull Motosports",
        creatorId: "AKedOLRHpi9_z8DhkczbgfnaWgDqmRed0HQe9glFV-qM",
        title: "The Most Challenging and Dangerous Category: The Bikes of the Dakar Rally",
        description:
            "The bike category of the Dakar Rally is a brutal category for riders, both physically and mentally. Will the KTM team be able to reclaim the title after losing their streak last year?",
        views: "95,054",
        category: "Dakar",
        uploadDate: "Jan 4, 2021",
    },
    {
        _id: "zMC7ASIEXNo",
        creator: "Simon Marcic",
        creatorId: "AKedOLSuoaMilD2UyuKupQ59D0dwusIP4GAuffXavHJPvw",
        title: "The best bike for the Dakar Rally | Vlog 21",
        description:
            "In this Vlog, I will show you my bike that I have raced the Dakar 2020 and will race the Dakar 2021 in Saudi Arabia. This bike is just awesome,  happy to say the best bike I have ridden a Dakar Rally with.",
        views: "18,545",
        category: "Dakar",
        uploadDate: "Jul 8, 2020",
    },
    {
        _id: "eo5OJY7dlGY",
        creator: "Brake Magazine",
        creatorId: "AKedOLQlE3hy8Q8KZPIsTEJ95d6yh5H9hFSjzrkjCvONuA",
        title: "Five Essential Dirt Bike Skills and Tips",
        description:
            "We love dirt bikes. They're literally the best type of motorbike. Riding off-road how is challenging, so we've put together an outline of the best tips and skills for riding dirt bikes.",
        views: "182,317",
        category: "Off Road Basics",
        uploadDate: "Apr 13, 2020",
    },
    {
        _id: "W0R4P2ynYhk",
        creator: "The Deegans",
        creatorId: "AKedOLSuoaMilD2UyuKupQ59D0dwusIP4GAuffXavHJPvw",
        title: "Brian Deegan Rides His Childhood Dirt Bike",
        description:
            "After The Wick, we checked out KAPLAN AMERICA and his sick Dirt Bike museum! They just so happened to have the same 1973 Honda MR50 from my childhood. Fully restored and ready to take for some hot laps! This was the first dirt bike I ever owned and is a part of so many great memories from being a kid. ",
        views: "186,686",
        category: "Travel",
        uploadDate: "Apr 23, 2022",
    },
    {
        _id: "C4ZrK8EJTnE",
        creator: "Nomad Sweden",
        creatorId: "AKedOLRIzxtWF4LZ3cUcQjlfTNTzRS8mRvQNH0kb1A2iJg",
        title: "Epic off-road adventure in Eastern Europe",
        description:
            "An epic off road adventure in eastern Europe through 13 countries. Minimal luggage and adventures of a life time in one single month.",
        views: "392,165",
        category: "Travel",
        uploadDate: "Jan 14, 2022",
    },
    {
        _id: "7NdVDhr6KTk",
        creator: "Nomad Sweden",
        creatorId: "AKedOLRIzxtWF4LZ3cUcQjlfTNTzRS8mRvQNH0kb1A2iJg",
        title: "Ultimate mobile navigation setup for adventure riding",
        description:
            "How do you use a smart phone or tablet, and still get a reliable solution for adventure motorcycle trips? This is my take on that problem.",
        views: "85,676",
        category: "Tips n Tricks",
        uploadDate: "Dec 5, 2020",
    },

    {
        _id: "5WJvQqeQpe8",
        creator: "FortNine",
        creatorId: "AKedOLSoxgXDjtLyoa4fW-Ya4Tt4sImuFqCY-4FZvTCn",
        title: "Is the Yamaha Ténéré 700 Really So Special?",
        description:
            "Too portly, too big, too gimmicky, too…well, everything. Adventure bikes have gotten out of hand. Yamaha wants to change that by offering something just right - nothing more, nothing less. ",
        views: "1,887,094",
        category: "Travel",
        uploadDate: "Jun 28, 2020",
    },
    {
        _id: "HP9OjCb7y5g",
        creator: "RevZilla",
        creatorId: "AKedOLTMIl-Vf-MadqQMx1OhXeuX8ATIEqLLxyr3viRyYA",
        title: "Cheapskate Escape! 2020 Royal Enfield Himalayan vs. 2020 CSC RX4 | CTXP",
        description: "Cheapskate Escape! 2020 Royal Enfield Himalayan vs. 2020 CSC RX4 | Common Tread XP Read ",
        views: "1,110,471",
        category: "Travel",
        uploadDate: "Jun 13, 2020",
    },
    {
        _id: "yVTjgZGBiZk",
        creator: "RevZilla",
        creatorId: "AKedOLTMIl-Vf-MadqQMx1OhXeuX8ATIEqLLxyr3viRyYA",
        title: "2022 Kawasaki KLR650 First Ride Review",
        description: "2022 Kawasaki KLR650 First Ride Review",
        views: "222,177",
        category: "Travel",
        uploadDate: "Sep 8, 2021",
    },
    {
        _id: "Geb_QFxp_hs",
        creator: "RevZilla",
        creatorId: "AKedOLTMIl-Vf-MadqQMx1OhXeuX8ATIEqLLxyr3viRyYA",
        title: "1,000 Miles Across Alaska! 1975 Honda CT90 vs. 2021 Trail 125 | CTXP",
        description:
            "North, to the future! In this episode of CTXP Ari and Zack take off across the Last Frontier to see just how far north they can get on tiny motorcycles. Yes, we know, c90adventures already did this and did it better. You might say the boys were so inspired that they wanted to have their own CT90 story to tell. Buckle up for a coast-to-coast Alaskan adventure and a journey beyond the end of the Dalton Highway, to the northernmost town in the United States.",
        views: "3,389,378",
        category: "Travel",
        uploadDate: "Nov 20, 2021",
    },
    {
        _id: "XgPpLKCUlbA",
        creator: "RevZilla",
        creatorId: "AKedOLTMIl-Vf-MadqQMx1OhXeuX8ATIEqLLxyr3viRyYA",
        title: "How To Clean & Lube Your Motorcycle Chain at Rev",
        description: "How To Clean & Lube Your Motorcycle Chain at Rev",
        views: "2,786,668",
        category: "Tips n Tricks",
        uploadDate: "Apr 9, 2016",
    },
    {
        _id: "8b31J9-VKug",
        creator: "FortNine",
        creatorId: "AKedOLSoxgXDjtLyoa4fW-Ya4Tt4sImuFqCY-4FZvTCn",
        title: "KTM 1290 Super Adventure R Review",
        description:
            "The KTM 1290 Super Adventure is a young species. We humans still have much to learn about this machine. But we' have seen goodness in it. Freedom is the right of all sentient beings. You all know there's only one way to achieve it: we must tame the KTM Super Adventure R. If all else fails, we will deploy backup. ",
        views: "1,422,059",
        category: "Tips n Tricks",
        uploadDate: "May 25, 2017",
    },
    {
        _id: "MC780VQPIK4",
        creator: "Nomad Sweden",
        creatorId: "AKedOLRIzxtWF4LZ3cUcQjlfTNTzRS8mRvQNH0kb1A2iJg",
        title: "Giant Loop ZigZag handlebar bag 2020 - Review",
        description: "Review of the Giant Loop ZigZag bag.Fits perfectly on any motorbike or enduro.",
        views: "7,410",
        category: "Tips n Tricks",
        uploadDate: "Dec 5, 2020",
    },
    {
        _id: "cm84WChWpxU",
        creator: "Nomad Sweden",
        creatorId: "AKedOLRIzxtWF4LZ3cUcQjlfTNTzRS8mRvQNH0kb1A2iJg",
        title: "Why the Honda AfricaTwin 1100 Adventure Sports 2020?",
        description:
            "Stefan and Tony are in the clouds with their new machines. But why did they change from their BMW and KTM to the Honda Africa Twin?",
        views: "35,002",
        category: "Travel",
        uploadDate: "Oct 25, 2020",
    },
    {
        _id: "uLj9WfoWPSQ",
        creator: "FortNine",
        creatorId: "AKedOLSoxgXDjtLyoa4fW-Ya4Tt4sImuFqCY-4FZvTCn",
        title: "Groundbreaking Motorcycle Helmets",
        description:
            "Yes, we realize the focus is on a different sort of PPE right now but hopefully this is all over soon and we can get back to buying the cool protective equipment we actually like - motorcycle gear. Here are some rad new motorbike helmets",
        views: "2,328,656",
        category: "Tips n Tricks",
        uploadDate: "Apr 15, 2020",
    },
    {
        _id: "ikMfS4gZ1Uc",
        creator: "RevZilla",
        creatorId: "AKedOLTMIl-Vf-MadqQMx1OhXeuX8ATIEqLLxyr3viRyYA",
        title: "Best Adventure Motorcycle Mods",
        description: "Best Adventure Motorcycle Modifications",
        views: "276,66",
        category: "Tips n Tricks",
        uploadDate: "Apr 9, 2017",
    },
    {
        _id: "tutdLZ0WqX0",
        creator: "FortNine",
        creatorId: "AKedOLSoxgXDjtLyoa4fW-Ya4Tt4sImuFqCY-4FZvTCn",
        title: "BMW F800GS Adventure Review",
        description:
            "RyanF9 reviews his own BMW F800GS Adventure. It's a motorcycle love story all right - but will it have a happy ending?",
        views: "1,665,697",
        category: "Tips n Tricks",
        uploadDate: "Oct 12, 2017",
    },
    {
        _id: "_ApPIEnAjns",
        creator: "FortNine",
        creatorId: "AKedOLSoxgXDjtLyoa4fW-Ya4Tt4sImuFqCY-4FZvTCn",
        title: "Who Killed Alta? The Tragedy of the Best Electric Motorcycle",
        description:
            "Lauded as the best electric dirt bike, the Alta Redshift only lived four years before the company went bankrupt. Who killed this futuristic motocross bike? And why?",
        views: "856,656",
        category: "Tips n Tricks",
        uploadDate: "Feb 19, 2020",
    },
];
