export const signupErrorActionTypes = {
    SET_FIRSTNAME_ERROR: "SET_FIRSTNAME_ERROR",
    SET_LASTNAME_ERROR: "SET_LASTNAME_ERROR",
    SET_EMAIL_ERROR: "SET_EMAIL_ERROR",
    SET_PASSWORD_ERROR: "SET_PASSWORD_ERROR",
    SET_CONFIRM_PASSWORD_ERROR: "SET_CONFIRM_PASSWORD_ERROR",
    SET_AGREE_ERROR: "SET_AGREE_ERROR",
    RESET_SIGNUP_ERRORS: "RESET_SIGNUP_ERRORS",
};

export const signupUserActiontypes = {
    SET_FIRSTNAME: "SET_FIRSTNAME",
    SET_LASTNAME: "SET_LASTNAME",
    SET_EMAIL: "SET_EMAIL",
    SET_PASSWORD: "SET_PASSWORD",
    SET_CONFIRM_PASSWORD: "SET_CONFIRM_PASSWORD",
    SET_AGREE_TO: "SET_AGREE_TO",
    RESET_NEW_USER_DATA: "RESET_NEW_USER_DATA",
};

export const authActionTypes = {
    SET_AUTH: "SET_AUTH",
    SET_LOGIN_ERROR: "SET_LOGIN_ERROR",
    SET_SIGNUP_ERROR: "SET_SIGNUP_ERROR",
    SET_AUTH_LOGOUT: "SET_AUTH_LOGOUT",
};
