export const signupErrorActionTypes = {
    SET_FIRSTNAME_ERROR: "SET_FIRSTNAME_ERROR",
    SET_LASTNAME_ERROR: "SET_LASTNAME_ERROR",
    SET_EMAIL_ERROR: "SET_EMAIL_ERROR",
    SET_PASSWORD_ERROR: "SET_PASSWORD_ERROR",
    SET_CONFIRM_PASSWORD_ERROR: "SET_CONFIRM_PASSWORD_ERROR",
    SET_AGREE_ERROR: "SET_AGREE_ERROR",
    RESET_SIGNUP_ERRORS: "RESET_SIGNUP_ERRORS",
};

export const signupUserActiontypes = {
    SET_FIRSTNAME: "SET_FIRSTNAME",
    SET_LASTNAME: "SET_LASTNAME",
    SET_EMAIL: "SET_EMAIL",
    SET_PASSWORD: "SET_PASSWORD",
    SET_CONFIRM_PASSWORD: "SET_CONFIRM_PASSWORD",
    SET_AGREE_TO: "SET_AGREE_TO",
    RESET_NEW_USER_DATA: "RESET_NEW_USER_DATA",
};

export const authActionTypes = {
    SET_AUTH: "SET_AUTH",
    SET_LOGIN_ERROR: "SET_LOGIN_ERROR",
    SET_SIGNUP_ERROR: "SET_SIGNUP_ERROR",
    SET_AUTH_LOGOUT: "SET_AUTH_LOGOUT",
};

export const videoActionTypes = {
    SET_VIDEOLIST: "SET_VIDEOLIST",
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
    SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
    SET_SEARCH_TXT: "SET_SEARCH_TXT",
    SET_SORT_BY_DATE: "SET_SORT_BY_DATE",
};

export const playlistsActionTypes = {
    SET_PLAYLISTS: "SET_PLAYLISTS",
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
    UPDATE_PLAYLIST: "UPDATE_PLAYLIST",
};

export const noteActionTypes = {
    SET_NOTES: "SET_NOTES",
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
    SET_VIDEO_ID: "SET_VIDEO_ID",
};

export const historyActionTypes = {
    SET_HISTORY_LIST: "SET_HISTORY_LIST",
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
};

export const watchLaterActionTypes = {
    SET_WATCHLATER_LIST: "SET_WATCHLATER_LIST",
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
};

export const likesActionTypes = {
    SET_LIKED_LIST: "SET_LIKED_LIST",
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
};
